In [1]:
# This Notebook Contains All Basic Numpy Operations
import numpy as np

In [2]:
# array in numpy
arr_1 = np.array([1,2,3,4,5,6])

In [3]:
print(arr_1.shape)
print(type(arr_1))

(6,)
<class 'numpy.ndarray'>


In [4]:
# difference between lists and numpy array
list_1 = [1,2,3,4,5,6]

In [5]:
print(type(list_1))
print(type(arr_1))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
print(arr_1)
print(list_1)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


+ Array Always Contains Same Kind Of Data Type
+ Array Always able to perform matrix operation
+ In deep learning these array reprsents matrix for matrix mainuplation
+ Array reprsents something like this [1 2 3 4 5 6 7]

In [7]:
# matrix operations
arr_1 = np.array([2,4,8])
arr_2 = np.array([3,9,27])

In [8]:
## Add
print(arr_1+arr_2)

[ 5 13 35]


In [9]:
## subtract
print(arr_2-arr_1)

[ 1  5 19]


In [14]:
## multiplication and others
print(arr_1*arr_2)

print(arr_1/arr_2)

print(arr_2//arr_1)

print(arr_2%arr_1)

[  6  36 216]
[0.66666667 0.44444444 0.2962963 ]
[1 2 3]
[1 1 3]


In [15]:
# Array as true false 
arr_1>0

array([ True,  True,  True])

In [18]:
# Print those elements of arr_1 which are greater then 2
arr_1[arr_1>2]

array([4, 8])

In [19]:
# Print those elements of arr_2 which are greater then elements of arr_1
arr_2[arr_2>arr_1]

array([ 3,  9, 27])

In [28]:
# Print those elements of arr_2 which are devisible by 9
arr_2[arr_2%9==0]

array([ 9, 27])

In [32]:
# Multidimensional Array
muArr_1 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='int64')
muArr_2 = np.array([[11,12,13],[14,15,16],[17,18,19]],dtype='int16')

In [38]:
# Matrix Operation And Array Analysis
print(muArr_1.shape)

print(muArr_2.shape)

print(type(muArr_1))

print(type(muArr_2))

(3, 3)
(3, 3)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [37]:
# Add
print(muArr_1+muArr_2)

# Subtract
print(muArr_1-muArr_2)

# Multiply
print(muArr_1*muArr_2)

# Devide
print(muArr_1/muArr_2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [39]:
# Array Slicing And Indexing

# Access arr_1 first two elements
print(arr_1[:2])

# Access arr_2 last two elements
print(arr_2[1:])

# Access muArr_1 last two rows
print(muArr_1[1:])

# Access muArr_2 first two rows
print(muArr_2[:2])

[2 4]
[ 9 27]
[[4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]]


In [43]:
# Write Slicing expression to print 5 from muArr_1
print(muArr_1[1][1])

print(muArr_1[1,1])

# Write Slicing expression to print 18 from muArr_2
print(muArr_2[2][1])

print(muArr_2[2,1])

5
5
18
18


In [50]:
# Print 2nd column from muArr_1
print(muArr_1[:,1])

# Print 1st column from muArr_2
print(muArr_2[:][1])

[2 5 8]
[14 15 16]


In [54]:
# Array Reassignment
arr_1[1] = 0
arr_2[2] = 19

In [55]:
print(arr_1)
print(arr_2)

[2 0 8]
[ 3  9 19]


In [58]:
# Numpy Built-in Fxns And Operations

# Range Function in array
arr_3 = np.arange(10,21,2)
print(arr_3)
print(type(arr_3))

[10 12 14 16 18 20]
<class 'numpy.ndarray'>


In [3]:
# Print Identity matrix of order 6*6

id_matrix=np.identity(6)
print(id_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [6]:
# Create an array of all zeros

zero_arr = np.zeros([2,3])
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Array Resizing

re_arr = np.resize(zero_arr,[3,2])
print(re_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
# Array Reshaping

reshape_arr = np.reshape(zero_arr,[1,6])
print(reshape_arr)

[[0. 0. 0. 0. 0. 0.]]


In [11]:
# Find indices of non-zero elements from [1,0,1,0,3,0,4,6,7,0,9,0,0,0]

non_zero = np.array([1,0,1,0,3,0,4,6,7,0,9,0,0,0])
print(np.nonzero(non_zero))

(array([ 0,  2,  4,  6,  7,  8, 10]),)


In [13]:
# Create a 3x3x4 array with random values

R = np.random.random((3,3,4))
print(R)

[[[0.93735306 0.0536313  0.49199918 0.59496317]
  [0.50277269 0.71895663 0.14601311 0.8412276 ]
  [0.26770108 0.96608135 0.16388517 0.16182858]]

 [[0.69207289 0.35749182 0.13414178 0.67659393]
  [0.8181274  0.84804245 0.13179145 0.31953123]
  [0.4136487  0.18656474 0.11813166 0.57401104]]

 [[0.19606099 0.76402682 0.63928486 0.16139194]
  [0.17255524 0.3328685  0.09094356 0.90353698]
  [0.64741795 0.96039613 0.28653818 0.75618619]]]


In [15]:
# Mean Of Array R

# Median Of Array R

# Standard Deviation Of Array R

# variance Of Array R
mean = np.mean(R)
median = np.median(R)
std_dev = np.std(R)
var = np.var(R)

In [16]:
print(mean)
print(median)
print(std_dev)
print(var)

0.47299359353703174
0.4528239420209515
0.2952236574030208
0.08715700789041621


In [19]:
# Stacking of array

X = np.arange(1,5).reshape(2,2)
Y = np.arange(5,9).reshape(2,2)

print(X)
print(Y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [27]:
# Horizontal Stacking

hstack = np.hstack([X,Y])
print(hstack)
print(hstack.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [30]:
# Vertical Stacking

vstack = np.vstack([X,Y])
print(vstack)
print(vstack.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [34]:
# Concatenation of array
v_con = np.concatenate((X,Y),axis=0)
h_con = np.concatenate((X,Y),axis=1)

In [35]:
print(h_con)
print(v_con)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
# Depth Stack
dstack = np.dstack([X,Y])
print(dstack)
print(dstack.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [39]:
# Matrix Multiplication
matrix_1 = np.matrix(range(1,10)).reshape(3,3)
matrix_2 = np.matrix(range(11,20)).reshape(3,3)

In [41]:
print(matrix_1)
print(matrix_2)
print(matrix_1.shape)
print(matrix_2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
(3, 3)
(3, 3)


In [42]:
# Matrix Multiplication

matrix_mul = matrix_1*matrix_2
print(matrix_mul)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [43]:
print(np.matmul(matrix_1,matrix_2))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [44]:
# Array Mainuplation

A = np.arange(1,10).reshape(3,3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
rav_arr = A.ravel()
print(rav_arr)

[1 2 3 4 5 6 7 8 9]


In [46]:
flat_arr = A.flatten()
print(flat_arr)

[1 2 3 4 5 6 7 8 9]


In [47]:
# Transpose Of Array
transpose = A.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [53]:
# Resizing Of The Array

resize_arr = np.resize(transpose,(1,12))
print(resize_arr)

[[1 4 7 2 5 8 3 6 9 1 4 7]]


In [54]:
# print minimum and maximum of an array

print(np.min(transpose))
print(np.max(transpose))

1
9


In [58]:
# create an array with similar interval

P = np.linspace(1,10,4)
print(P)

[ 1.  4.  7. 10.]
